workflows:
  ios-workflow:
    name: iOS DurakAI Build
    environment:
      xcode: 16.0
      vars:
        XCODE_PROJECT: "DurakAI.xcodeproj"
        XCODE_SCHEME: "DurakAI"
    scripts:
      - name: Build archive
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/DurakAI.xcarchive \
            archive
      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/DurakAI.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $CM_BUILD_DIR/ipa
    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
      - $CM_BUILD_DIR/ipa/*.dSYM.zip
      - $CM_BUILD_DIR/ipa/*.app
    publishing:
      email:
        recipients:
          - your_email@example.com
        notify:
          success: true
          failure: true