workflows:
  ios-app:
    name: Build unsigned .ipa
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Build .ipa
        script: |
          xcodebuild \
            -project "DurakAI.xcodeproj" \
            -scheme "DurakAI" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/DurakAI.xcarchive \
            archive

          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/DurakAI.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $CM_BUILD_DIR/ipa
    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
